### ISSUE TITLE
Selected an existing folder to save bookmarks into will delete all the preexisting bookmarks in that folder

### ISSUE THREAD

**Issue by spiralsam** [salvoventura/save-my-tabs#2]
Instead of adding bookmarks into that folder, bookmarks are completely replaced. If this is meant to happen, maybe there can be an option to append them instead.

**Comment by salvoventura** [comment]
@spiralsam That's correct: this behavior is by design, however I'll look into adding an option. Thanks for reporting this and the other issues/requests!

**Comment by salvoventura** [comment]
Changed default behavior to _append_ . Provided option to perform a _replace all_ .
