### ISSUE TITLE
Instructions on how to build the final extension file

### ISSUE THREAD

**Issue by SirWindfield** [salvoventura/save-my-tabs#9]
Hey! I can't seem to find any resources on how the final browser extension file has to be build. The one that you download from the web store.

**Comment by salvoventura** [comment]
Hello,
 nothing special, some detail depends on the web store you publish to. I recommend you start by reading this tutorial:
 
 https://extensionworkshop.com/documentation/publish/package-your-extension/

 Cheers,
 Salvatore
